import {walkerSnapshot,mixer} from './fixtures';
import {fixture} from './portalFixtures';
const success=(data:unknown)=>Promise.resolve({data,error:null});
const unavailable=()=>Promise.resolve({data:null,error:{message:'This action requires a connected installation. The website uses sample data.'}});
const lighting={project_id:"sample",device_id:"sample",bridge_ready:true,bridge_version:"sample",state_revision:1,requested_intensity:134,controller_intensity:134,last_nonzero_intensity:134,last_source:"portal",hardware_verification:"unavailable",controller_process_started_at:new Date().toISOString(),remote_control_allowed:true,last_command:null};
const schedules:any[]=[];
export const supabase={
 rpc(name:string,args:any={}){if(name==="lighting_native_status")return success({...lighting,last_bridge_at:new Date().toISOString()});if(name==="chamber_schedule_overview")return success({schedules,runs:[],can_control:true,scheduler_online:true});if(name==="chamber_schedule_save"){const item={...args.definition,id:args.schedule_id||`sample-${schedules.length+1}`,owner:"Sample",next_run_at:null,version:1,can_resume:true};const index=schedules.findIndex(s=>s.id===item.id);if(index<0)schedules.push(item);else schedules[index]=item;return success({ok:true});}if(name==="chamber_schedule_delete"){const index=schedules.findIndex(s=>s.id===args.p_schedule_id);if(index>=0)schedules.splice(index,1);return success({ok:true});}if(name==="chamber_schedule_pause"||name==="chamber_schedule_resume"){const s=schedules.find(s=>s.id===args.p_schedule_id);if(s)s.enabled=name.endsWith("resume");return success({ok:true});}if(name.startsWith('walker_live_observation_'))return success(walkerSnapshot());if(name==='gas_mixer_native_status')return success({...mixer,last_bridge_at:new Date().toISOString()});if(name==='gas_mixer_remote_status')return success({project_id:'sample',device_id:'sample',device_name:'Gas Mixer',online:true,last_seen_at:new Date().toISOString(),remote_control_allowed:true,active_session:false,active_controller_email:null});return unavailable();},
 functions:{invoke(name:string,options:any){if(name==="lighting-native-control"){lighting.requested_intensity=options.body.intensity;lighting.controller_intensity=options.body.intensity;lighting.state_revision++;return success({ok:true,command:{id:"sample",status:"observed",intensity:options.body.intensity}});}if(name==='gas-mixer-native-control'){const {field,value}=options.body;if(field==='total_slpm'||field==='use_licor')(mixer.requested_state as any)[field]=value;else{const [,address,prop]=field.split('.');(mixer.requested_state.channels as any)[address][prop]=value;}mixer.state_revision++;return success({ok:true,command:{id:'sample',status:'verified'},requested_state:mixer.requested_state});}return unavailable();}},
 from(table:string){let rows:any[]=table==='sensor_readings'?fixture.data.readings:table==='pairings'?fixture.data.pairings:[];const q:any=new Proxy({}, {get(_t,key){if(key==='then')return (resolve:any)=>resolve({data:rows,error:null});if(key==='single'||key==='maybeSingle')return ()=>success(rows[0]||null);return ()=>q;}});return q;},
 auth:{getSession:()=>success({session:null}),signOut:()=>success(null),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},
 channel(){return {on(){return this},subscribe(){return this}}},removeChannel(){},
};
