-- Pot notes and versioned bench layouts for the portal.
--
-- Additive only. Nothing here changes controller configuration, targets, pairings, calibration,
-- schedules, readings, valve events or the canonical identity tables (physical_positions,
-- research_pots, hardware_bindings are read, never written). Both tables are append-only:
-- a note is corrected by a new note that supersedes it; a layout is changed by a new version.
--
-- Rollback (no other object depends on these): drop table public.portal_bench_layout_versions;
-- drop table public.portal_pot_notes; drop function public.has_portal_project_role(uuid, text[]);
-- drop function public.portal_pot_notes_before_insert(); drop function
-- public.portal_bench_layout_versions_before_insert(). Take a backup of both tables first
-- if they hold rows.

-- Role check scoped to project (not gas-mixer-only) access. current_portal_role ignores
-- access_scope, so policies here never use it.
create or replace function public.has_portal_project_role(check_project_id uuid, allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.portal_access access
    where access.project_id = check_project_id
      and access.user_id = (select auth.uid())
      and access.access_scope = 'project'
      and access.role = any (allowed_roles)
  );
$$;

revoke all on function public.has_portal_project_role(uuid, text[]) from public, anon;
grant execute on function public.has_portal_project_role(uuid, text[]) to authenticated, service_role;

-- ---------------------------------------------------------------- pot notes

create table if not exists public.portal_pot_notes (
  -- Generated by the writer's device so an offline retry can never create a duplicate.
  id uuid primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  device_id text not null references public.devices(id) on delete cascade,
  -- The controller pairing the note is about (Zone<z>-Pot<p>), and the physical research pot
  -- it was bound to when the note was written, when one was known.
  pairing_name text not null check (char_length(pairing_name) between 1 and 120),
  research_pot_id uuid,
  experiment_id uuid,
  body text not null check (char_length(btrim(body)) between 1 and 2000),
  tags text[] not null default '{}'::text[]
    check (cardinality(tags) <= 8 and array_position(tags, null) is null),
  -- When the person wrote it (their device's clock), and when the database received it.
  observed_at timestamptz not null,
  recorded_at timestamptz not null default now(),
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  -- Shown to other members, who cannot read each other's profiles.
  author_label text not null check (char_length(author_label) between 1 and 200),
  -- A correction points at the note it replaces; the original stays in the record.
  supersedes_id uuid references public.portal_pot_notes(id) on delete restrict,
  client_context jsonb not null default '{}'::jsonb check (jsonb_typeof(client_context) = 'object'),
  constraint portal_pot_notes_id_project_unique unique (id, project_id),
  constraint portal_pot_notes_research_pot_fk foreign key (research_pot_id, project_id)
    references public.research_pots(id, project_id) on delete restrict,
  constraint portal_pot_notes_experiment_fk foreign key (experiment_id, project_id)
    references public.experiments(id, project_id) on delete restrict
);

create index if not exists portal_pot_notes_pot_idx
  on public.portal_pot_notes (project_id, device_id, pairing_name, observed_at desc);
create index if not exists portal_pot_notes_project_time_idx
  on public.portal_pot_notes (project_id, observed_at desc);

create or replace function public.portal_pot_notes_before_insert()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  writer_email text;
begin
  -- The author and receive time are the database's, not the client's.
  new.created_by := (select auth.uid());
  new.recorded_at := now();
  if new.created_by is null then
    raise exception 'A signed-in portal member is required to write a note.' using errcode = '42501';
  end if;
  select access.email into writer_email
  from public.portal_access access
  where access.project_id = new.project_id
    and access.user_id = new.created_by
    and access.access_scope = 'project'
  limit 1;
  new.author_label := coalesce(writer_email, new.author_label);
  if not exists (select 1 from public.devices device where device.id = new.device_id and device.project_id = new.project_id) then
    raise exception 'The controller does not belong to this project.' using errcode = '23514';
  end if;
  -- Offline notes may arrive late, but not from the future or from long ago.
  if new.observed_at > now() + interval '10 minutes' or new.observed_at < now() - interval '45 days' then
    raise exception 'The note time is outside the accepted window.' using errcode = '23514';
  end if;
  if new.supersedes_id is not null and not exists (
    select 1 from public.portal_pot_notes previous
    where previous.id = new.supersedes_id and previous.project_id = new.project_id
      and previous.pairing_name = new.pairing_name
  ) then
    raise exception 'A correction must supersede a note about the same pot.' using errcode = '23514';
  end if;
  new.body := btrim(new.body);
  return new;
end;
$$;

revoke all on function public.portal_pot_notes_before_insert() from public, anon, authenticated;

drop trigger if exists portal_pot_notes_before_insert on public.portal_pot_notes;
create trigger portal_pot_notes_before_insert
  before insert on public.portal_pot_notes
  for each row execute function public.portal_pot_notes_before_insert();

alter table public.portal_pot_notes enable row level security;

drop policy if exists "portal members read pot notes" on public.portal_pot_notes;
create policy "portal members read pot notes"
  on public.portal_pot_notes for select to authenticated
  using (public.has_portal_access(project_id));

drop policy if exists "researchers and admins add pot notes" on public.portal_pot_notes;
create policy "researchers and admins add pot notes"
  on public.portal_pot_notes for insert to authenticated
  with check (
    created_by = (select auth.uid())
    and public.has_portal_project_role(project_id, array['admin', 'researcher'])
  );

revoke all on public.portal_pot_notes from public, anon, authenticated;
grant select, insert on public.portal_pot_notes to authenticated;
grant select, insert, update, delete on public.portal_pot_notes to service_role;

-- ---------------------------------------------------------------- bench layouts

create table if not exists public.portal_bench_layout_versions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  device_id text not null references public.devices(id) on delete cascade,
  version integer not null check (version > 0),
  -- { "benches": [{ "id", "label", "rows", "columns" }], "positions": [{ "pairing_name", "bench", "row", "column" }] }
  layout jsonb not null check (jsonb_typeof(layout) = 'object'),
  -- 'recorded': a person recorded where the pots stand. It is never called measured or verified;
  -- physical confirmation stays in hardware_bindings.
  basis text not null default 'recorded' check (basis in ('recorded')),
  note text check (note is null or char_length(note) <= 500),
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  author_label text not null check (char_length(author_label) between 1 and 200),
  created_at timestamptz not null default now(),
  constraint portal_bench_layout_versions_unique unique (project_id, device_id, version)
);

create or replace function public.portal_bench_layout_versions_before_insert()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  writer_email text;
  bench jsonb;
  entry jsonb;
  bench_ids text[] := '{}';
  seen_pots text[] := '{}';
  seen_cells text[] := '{}';
  cell text;
begin
  new.created_by := (select auth.uid());
  new.created_at := now();
  if new.created_by is null then
    raise exception 'A signed-in administrator is required to record a layout.' using errcode = '42501';
  end if;
  if not exists (select 1 from public.devices device where device.id = new.device_id and device.project_id = new.project_id) then
    raise exception 'The controller does not belong to this project.' using errcode = '23514';
  end if;
  select access.email into writer_email
  from public.portal_access access
  where access.project_id = new.project_id and access.user_id = new.created_by and access.access_scope = 'project'
  limit 1;
  new.author_label := coalesce(writer_email, new.author_label);

  if jsonb_typeof(new.layout -> 'benches') <> 'array' or jsonb_typeof(new.layout -> 'positions') <> 'array'
     or jsonb_array_length(new.layout -> 'benches') not between 1 and 50
     or jsonb_array_length(new.layout -> 'positions') > 2000 then
    raise exception 'A layout needs 1–50 benches and at most 2000 positions.' using errcode = '23514';
  end if;
  for bench in select * from jsonb_array_elements(new.layout -> 'benches') loop
    if jsonb_typeof(bench -> 'id') <> 'string' or char_length(bench ->> 'id') not between 1 and 40
       or jsonb_typeof(bench -> 'rows') <> 'number' or (bench ->> 'rows')::int not between 1 and 100
       or jsonb_typeof(bench -> 'columns') <> 'number' or (bench ->> 'columns')::int not between 1 and 100
       or (bench ->> 'id') = any (bench_ids) then
      raise exception 'Each bench needs a unique id and 1–100 rows and columns.' using errcode = '23514';
    end if;
    bench_ids := bench_ids || (bench ->> 'id');
  end loop;
  for entry in select * from jsonb_array_elements(new.layout -> 'positions') loop
    if jsonb_typeof(entry -> 'pairing_name') <> 'string'
       or not ((entry ->> 'bench') = any (bench_ids))
       or jsonb_typeof(entry -> 'row') <> 'number' or jsonb_typeof(entry -> 'column') <> 'number' then
      raise exception 'Each position needs a pot, one of the benches, a row and a column.' using errcode = '23514';
    end if;
    if exists (
      select 1 from jsonb_array_elements(new.layout -> 'benches') b
      where b ->> 'id' = entry ->> 'bench'
        and ((entry ->> 'row')::int not between 1 and (b ->> 'rows')::int
          or (entry ->> 'column')::int not between 1 and (b ->> 'columns')::int)
    ) then
      raise exception 'A position lies outside its bench.' using errcode = '23514';
    end if;
    cell := concat_ws(':', entry ->> 'bench', entry ->> 'row', entry ->> 'column');
    if (entry ->> 'pairing_name') = any (seen_pots) or cell = any (seen_cells) then
      raise exception 'Each pot and each place may appear once.' using errcode = '23514';
    end if;
    seen_pots := seen_pots || (entry ->> 'pairing_name');
    seen_cells := seen_cells || cell;
  end loop;

  -- Versions are assigned here, one after another, regardless of what the client sent.
  perform pg_advisory_xact_lock(hashtextextended('portal_bench_layout:' || new.project_id::text || ':' || new.device_id, 0));
  select coalesce(max(version), 0) + 1 into new.version
  from public.portal_bench_layout_versions
  where project_id = new.project_id and device_id = new.device_id;
  return new;
end;
$$;

revoke all on function public.portal_bench_layout_versions_before_insert() from public, anon, authenticated;

drop trigger if exists portal_bench_layout_versions_before_insert on public.portal_bench_layout_versions;
create trigger portal_bench_layout_versions_before_insert
  before insert on public.portal_bench_layout_versions
  for each row execute function public.portal_bench_layout_versions_before_insert();

alter table public.portal_bench_layout_versions enable row level security;

drop policy if exists "portal members read bench layouts" on public.portal_bench_layout_versions;
create policy "portal members read bench layouts"
  on public.portal_bench_layout_versions for select to authenticated
  using (public.has_portal_access(project_id));

drop policy if exists "admins record bench layouts" on public.portal_bench_layout_versions;
create policy "admins record bench layouts"
  on public.portal_bench_layout_versions for insert to authenticated
  with check (
    created_by = (select auth.uid())
    and public.has_portal_project_role(project_id, array['admin'])
  );

revoke all on public.portal_bench_layout_versions from public, anon, authenticated;
grant select, insert on public.portal_bench_layout_versions to authenticated;
grant select, insert, update, delete on public.portal_bench_layout_versions to service_role;

-- Live updates: notes written on one phone appear on other screens.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'portal_pot_notes'
     ) then
    alter publication supabase_realtime add table public.portal_pot_notes;
  end if;
end;
$$;

notify pgrst, 'reload schema';
